services:
    web:
        build: .
        ports:
            - '8080:80'
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: dvwa
            MYSQL_USER: dvwa
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '--silent']
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    db_data:
